# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f1472ff268609a0c86f5871730e8a0d5089388bbe0a9cdc0747e2215decb6ecbcae8a26efb4046f5ba3cc246e3326108c56672ef4ac8b34e1a3806ac1f531c

test:
  secret_key_base: 91d2c0ead3c2421608de8634bc7d0c15793a95a7a31470825c3143a458b918d581b26b98ca902dc7107aa507ff5412f5bd997c49d375fd59da0a73cb0cd33e0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
